let current = 0;
const stage = document.querySelector('#stage');
const jump = document.querySelector('#jump');
const list = document.querySelector('#slide-list');
slideData.forEach((s,i)=>{const option=document.createElement('option');option.value=i;option.textContent=`${i+1} · ${s.title}`;jump.append(option);const btn=document.createElement('button');btn.textContent=option.textContent;btn.type='button';btn.addEventListener('click',()=>{go(i);toggleList(false)});list.append(btn)});
function markup(s,i){
 const head=`<p class="label">${s.label}</p><h1>${s.title}</h1>`;
 let body='';
 if(s.mode==='complete')body=`<div class="complete-figure"><button class="image-button" data-zoom="assets/${s.image}.png" aria-label="放大完整原圖"><img src="assets/${s.image}.png" alt="${s.title}，含全部分圖與完整圖說"></button><p class="complete-caption">完整原圖與圖說 · 點圖放大 · 下一張分區解讀</p></div>`;
 else if(s.mode==='detail')body=`<div class="detail-layout"><div class="detail-visual"><button class="image-button" data-zoom="assets/${s.image}.png" aria-label="放大此分區"><img src="assets/${s.image}.png" alt="${s.title}原圖裁切放大"></button><div class="locator"><span>原圖位置</span><div class="locator-image"><img src="assets/${s.parent}.png" alt="分區在原圖的位置"><span class="region" style="left:${s.region[0]}%;top:${s.region[1]}%;width:${s.region[2]}%;height:${s.region[3]}%"></span></div><button class="text-button" data-zoom="assets/${s.parent}.png">查看完整原圖 ↗</button></div></div><div class="body">${s.body}</div></div>`;
 else if(s.photo)body=`<div class="photo-layout"><div class="body">${s.body}</div><img class="cover-photo" src="assets/${s.photo}" alt="陽光穿過樹林的免費自然配圖"></div>`;
 else body=`<div class="body">${s.body}</div>`;
 return `<article class="slide ${s.mode||'text'}" aria-label="第 ${i+1} 張">${head}${body}<p class="source">${s.source}</p></article>`
}
function go(i,update=true){current=Math.max(0,Math.min(slideData.length-1,i));stage.innerHTML=markup(slideData[current],current);jump.value=current;document.querySelector('#counter').textContent=`${current+1} / ${slideData.length}`;document.querySelector('#prev').disabled=current===0;document.querySelector('#next').disabled=current===slideData.length-1;if(update)history.replaceState(null,'',`#slide-${current+1}`);window.scrollTo(0,0)}
function readHash(){const n=Number(location.hash.replace('#slide-',''));go(Number.isInteger(n)&&n>0?n-1:0,false)}
function toggleList(open){list.hidden=!open;document.querySelector('#overview').setAttribute('aria-expanded',String(open))}
async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.body.requestFullscreen)await document.body.requestFullscreen()}catch(e){document.querySelector('.hint').textContent='此瀏覽器未允許全螢幕；仍可直接翻頁閱讀。'}}
document.querySelector('#prev').addEventListener('click',()=>go(current-1));document.querySelector('#next').addEventListener('click',()=>go(current+1));jump.addEventListener('change',()=>go(Number(jump.value)));document.querySelector('#overview').addEventListener('click',()=>toggleList(list.hidden));document.querySelector('#fullscreen').addEventListener('click',fullscreen);document.addEventListener('fullscreenchange',()=>{document.querySelector('#fullscreen').textContent=document.fullscreenElement?'離開全螢幕':'全螢幕'});
document.addEventListener('keydown',e=>{if(zoom.open||e.target.closest('select,input,textarea')||e.altKey||e.ctrlKey||e.metaKey)return;if(e.key===' '&&e.target.closest('button,a'))return;if(['ArrowRight','PageDown',' ','ArrowLeft','PageUp','Home','End'].includes(e.key))e.preventDefault();if(['ArrowRight','PageDown',' '].includes(e.key))go(current+1);if(['ArrowLeft','PageUp'].includes(e.key))go(current-1);if(e.key==='Home')go(0);if(e.key==='End')go(slideData.length-1);if(e.key.toLowerCase()==='f')fullscreen()});
let start=null;stage.addEventListener('touchstart',e=>{const t=e.changedTouches[0];start={x:t.clientX,y:t.clientY}}, {passive:true});stage.addEventListener('touchend',e=>{if(!start)return;const t=e.changedTouches[0],dx=t.clientX-start.x,dy=t.clientY-start.y;if(Math.abs(dx)>70&&Math.abs(dx)>Math.abs(dy)*1.5)go(current+(dx<0?1:-1));start=null},{passive:true});window.addEventListener('hashchange',readHash);window.addEventListener('beforeprint',()=>{stage.innerHTML=slideData.map(markup).join('')});window.addEventListener('afterprint',()=>go(current,false));readHash();

const zoom=document.querySelector('#image-zoom');stage.addEventListener('click',e=>{const btn=e.target.closest('[data-zoom]');if(!btn)return;zoom.querySelector('img').src=btn.dataset.zoom;zoom.showModal()});document.querySelector('#close-zoom').addEventListener('click',()=>zoom.close());zoom.addEventListener('click',e=>{if(e.target===zoom)zoom.close()});
